"""Create Invoice table with username

Revision ID: 96447bcfa1ef
Revises: ef79f133d956
Create Date: 2025-11-11 16:41:42.566774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96447bcfa1ef'
down_revision = 'ef79f133d956'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_token', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=6),
               existing_nullable=False)

    with op.batch_alter_table('register_token', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=6),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register_token', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.String(length=6),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('login_token', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.String(length=6),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###
