"""empty message

Revision ID: fbec66e94851
Revises: ae7647d16405
Create Date: 2025-10-28 17:13:16.275220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbec66e94851'
down_revision = 'ae7647d16405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register_token', schema=None) as batch_op:
        # give the constraint a proper name instead of None
        batch_op.create_unique_constraint('uq_register_token_token', ['token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register_token', schema=None) as batch_op:
        batch_op.drop_constraint('uq_register_token_token', type_='unique')
    # ### end Alembic commands ###
